let lang = localStorage.getItem("sunsetHunterLang") || null;
const T = {
  en: {
    title:"🌅 Sunset Hunter",
    sub:"Sunrise & sunset color prediction — find places with the best chance of dramatic pink, orange and red skies.",
    search:"Search",locate:"Use my location",date:"From",forecast:"Forecast",
    d3:"Next 3 days",d7:"Next 7 days",start:"Search for a city to begin.",
    score:"Score",best:"BEST DAY",sunset:"Sunset",sunrise:"Sunrise",
    high:"High cloud",mid:"Mid cloud",low:"Low cloud",rain:"Rain chance",vis:"Visibility",hum:"Humidity",
    excellent:"Exceptional 🔥",very:"Excellent ⭐",promising:"Very promising 👍",possible:"Possible",lowchance:"Low chance",
    how:"How the score works",
    tip:"The model looks for a useful combination of <b>high and middle cloud</b> (the best canvas) and rewards when both layers are present. It penalizes excessive low cloud and rain, while factoring in visibility and moderate humidity. Applied separately to sunrise and sunset times. Result is a <b>0–100 Score</b> — not a guarantee.",
    loading:"Loading forecast…",finding:"Finding place…",notfound:"Place not found.",fail:"Could not load the forecast.",
    sunsetDir:"Sunset direction",sunriseDir:"Sunrise direction",solarNoon:"Solar noon",elevation:"Elevation",
    solarAlt:"Solar altitude",viewDir:"Best viewing direction",horizon:"Horizon",
    openSky:"Open horizon (terrain DEM not loaded)",
    solarNote:"Solar position is calculated locally. The map contains no weather layer.",
    solarHint:"Sunrise / sunset direction and solar path",
    today:"Today",tomorrow:"Tomorrow",pick:"Select a location",
    rank:"Rank",dateCol:"Date",verdict:"Verdict",
    sunriseScore:"Sunrise Score",sunsetScore:"Sunset Score",
    styleTitle:"Sunset style",
    styleGold:"Golden-leaning",
    styleFire:"Fire-cloud / orange-red",
    stylePink:"Pink-leaning",
    styleRainbow:"Rainbow possible",
    styleDull:"Likely muted",
    styleNormal:"Ordinary glow",
    photoTitle:"📸 Photography Tips",
    photoBody:`<p style=\"margin-bottom:10px;color:var(--text-muted);font-size:.9rem\">Golden hour ≈ first 45–60 min after sunrise / last 45–60 min before sunset.</p><div class=\"settings\"><div class=\"set-item\"><b>ISO</b>100–400 (tripod: 100)</div><div class=\"set-item\"><b>Aperture</b>f/8–f/11 landscape · f/1.8–f/4 portrait</div><div class=\"set-item\"><b>Shutter</b>1/125+ handheld · slower on tripod</div><div class=\"set-item\"><b>White Balance</b>Cloudy / Shade (warm tones)</div><div class=\"set-item\"><b>Format</b>RAW always</div><div class=\"set-item\"><b>Exposure</b>−0.3 to −1 EV (protect sky)</div></div><ul><li><b>Arrive early</b> — be on location 20–30 min before sunrise / sunset.</li><li><b>Composition</b> — rule of thirds; put horizon on lower or upper third. Use foreground for depth.</li><li><b>Silhouette</b> — expose for the sky; let subjects go dark against the color.</li><li><b>Starburst</b> — small aperture (f/16) + sun just at edge of frame.</li><li><b>Stay longer</b> — best color often peaks 10–20 min after the sun dips / rises.</li><li><b>Phone tip</b> — use HDR or Pro mode, lock exposure on the bright sky, then recompose.</li></ul>`
  },
  zh: {
    title:"🌅 晚霞獵人",
    sub:"日出與晚霞預測——尋找最有機會出現粉紅、橘紅與壯觀天空的地方。",
    search:"搜尋",locate:"使用我的位置",date:"起始日期",forecast:"預測天數",
    d3:"未來 3 天",d7:"未來 7 天",start:"請搜尋一個城市開始。",
    score:"指數",best:"最佳預測日",sunset:"日落",sunrise:"日出",
    high:"高雲",mid:"中雲",low:"低雲",rain:"降雨機率",vis:"能見度",hum:"濕度",
    excellent:"極佳 🔥",very:"非常值得 ⭐",promising:"很有機會 👍",possible:"有機會",lowchance:"機會偏低",
    how:"指數怎麼算？",
    tip:"模型會尋找適量的<b>高雲與中雲</b>（最佳畫布），並在兩者同時出現時額外加分。同時降低低雲與降雨的遮蔽影響，也會考慮能見度與適中濕度。日出與日落分別計算。結果是 <b>0～100 指數</b>，不是保證。",
    loading:"正在載入預報……",finding:"正在尋找地點……",notfound:"找不到這個地點。",fail:"無法取得預報。",
    sunsetDir:"日落方向",sunriseDir:"日出方向",solarNoon:"太陽正午",elevation:"海拔",
    solarAlt:"太陽高度角",viewDir:"最佳觀看方向",horizon:"地平線",
    openSky:"開闊地平線（尚未載入地形 DEM）",
    solarNote:"太陽位置由本地計算；地圖不含氣象圖層。",
    solarHint:"日出／日落方向與太陽路徑",
    today:"今天",tomorrow:"明天",pick:"請選擇地點",
    rank:"排名",dateCol:"日期",verdict:"評價",
    sunriseScore:"日出指數",sunsetScore:"晚霞指數",
    styleTitle:"晚霞風格",
    styleGold:"偏黃金日落",
    styleFire:"偏火燒雲／橘紅",
    stylePink:"偏粉紅",
    styleRainbow:"有彩虹機會",
    styleDull:"平淡機會高",
    styleNormal:"一般晚霞",
    photoTitle:"📸 攝影技巧",
    photoBody:`<p style=\"margin-bottom:10px;color:var(--text-muted);font-size:.9rem\">黃金時刻 ≈ 日出後 45–60 分鐘 / 日落前 45–60 分鐘。</p><div class=\"settings\"><div class=\"set-item\"><b>ISO</b>100–400（腳架可鎖 100）</div><div class=\"set-item\"><b>光圈</b>風景 f/8–f/11 · 人像 f/1.8–f/4</div><div class=\"set-item\"><b>快門</b>手持 ≥1/125 · 腳架可更慢</div><div class=\"set-item\"><b>白平衡</b>陰天 / 陰影（偏暖）</div><div class=\"set-item\"><b>格式</b>一律拍 RAW</div><div class=\"set-item\"><b>曝光</b>−0.3～−1 EV（保護天空）</div></div><ul><li><b>提早到場</b> — 日出／日落前 20–30 分鐘就定位好。</li><li><b>構圖</b> — 三分法，地平線放在上或下 1/3。用前景增加層次。</li><li><b>剪影</b> — 對天空測光，讓主體變成深色輪廓。</li><li><b>星芒</b> — 小光圈 f/16，太陽剛擦到畫面邊緣。</li><li><b>多待一會兒</b> — 最美的顏色常出現在太陽升起／落下後 10–20 分鐘。</li><li><b>手機技巧</b> — 開 HDR 或專業模式，先對亮部天空鎖定曝光再構圖。</li></ul>`
  }
};
