let lang = localStorage.getItem("sunsetHunterLang") || null;
const T = {
  en: {
    title:"🌅 Sunset Hunter",
    sub:"Sunrise & sunset color prediction — find places with the best chance of dramatic pink, orange and red skies.",
    search:"Search",locate:"Use my location",date:"From",forecast:"Forecast",
    d3:"Next 3 days",d7:"Next 7 days",start:"Search for a city to begin.",
    score:"Score",best:"BEST DAY",sunset:"Sunset",sunrise:"Sunrise",
    high:"High cloud",mid:"Mid cloud",low:"Low cloud",rain:"Rain chance",vis:"Visibility",hum:"Humidity",
    excellent:"Exceptional 🔥",very:"Excellent ⭐",promising:"Very promising 👍",possible:"Possible",lowchance:"Low chance",
    how:"How the score works",
    tip:"<b>Score formula (0–100)</b><br>S = 0.28·H* + 0.16·M* + 0.14·√(H*·M*) + 0.15·L* + 0.11·R* + 0.10·V* + 0.06·U* + postRain<br>where * = ideal-range score; H/M = high/mid cloud (canvas); L = open low cloud; R = not too rainy; V = visibility; U = humidity. Light rain (10–35%) after clearing adds a small bonus. Sunrise and sunset use their own hour.",
    loading:"Loading forecast…",finding:"Finding place…",notfound:"Place not found.",fail:"Could not load the forecast.",
    sunsetDir:"Sunset direction",sunriseDir:"Sunrise direction",solarNoon:"Solar noon",elevation:"Elevation",
    solarAlt:"Solar altitude",viewDir:"Best viewing direction",horizon:"Horizon",
    openSky:"Open horizon (terrain DEM not loaded)",
    solarNote:"Solar position is calculated locally. The map contains no weather layer.",
    solarHint:"Sunrise / sunset direction and solar path",
    today:"Today",tomorrow:"Tomorrow",pick:"Select a location",
    rank:"Rank",dateCol:"Date",verdict:"Verdict",
    sunriseScore:"Sunrise Score",sunsetScore:"Sunset Score",
    styleTitle:"Sunset style",
    styleGold:"Golden-leaning",
    styleFire:"Fire-cloud / orange-red",
    stylePink:"Pink-leaning",
    styleRainbow:"Rainbow possible",
    styleDull:"Likely muted",
    styleNormal:"Ordinary glow",
    photoTitle:"📸 Photography Tips",
    photoBody:`photo tips en`
  },
  zh: {
    title:"🌅 晚霞獵人",
    sub:"日出與晚霞預測——尋找最有機會出現粉紅、橘紅與壯觀天空的地方。",
    search:"搜尋",locate:"使用我的位置",date:"起始日期",forecast:"預測天數",
    d3:"未來 3 天",d7:"未來 7 天",start:"請搜尋一個城市開始。",
    score:"指數",best:"最佳預測日",sunset:"日落",sunrise:"日出",
    high:"高雲",mid:"中雲",low:"低雲",rain:"降雨機率",vis:"能見度",hum:"濕度",
    excellent:"極佳 🔥",very:"非常值得 ⭐",promising:"很有機會 👍",possible:"有機會",lowchance:"機會偏低",
    how:"指數怎麼算？",
    tip:"<b>指數算式（0～100）</b><br>S = 0.28·H* + 0.16·M* + 0.14·√(H*·M*) + 0.15·L* + 0.11·R* + 0.10·V* + 0.06·U* + 雨後加分<br>* = 理想區間分數；H/M = 高／中雲（畫布）；L = 低雲不要太厚；R = 不要整片下雨；V = 能見度；U = 濕度。降雨 10–35% 且低雲不厚時略加分。日出與日落用各自時段。",
    loading:"正在載入預報……",finding:"正在尋找地點……",notfound:"找不到這個地點。",fail:"無法取得預報。",
    sunsetDir:"日落方向",sunriseDir:"日出方向",solarNoon:"太陽正午",elevation:"海拔",
    solarAlt:"太陽高度角",viewDir:"最佳觀看方向",horizon:"地平線",
    openSky:"開闊地平線（尚未載入地形 DEM）",
    solarNote:"太陽位置由本地計算；地圖不含氣象圖層。",
    solarHint:"日出／日落方向與太陽路徑",
    today:"今天",tomorrow:"明天",pick:"請選擇地點",
    rank:"排名",dateCol:"日期",verdict:"評價",
    sunriseScore:"日出指數",sunsetScore:"晚霞指數",
    styleTitle:"晚霞風格",
    styleGold:"偏黃金日落",
    styleFire:"偏火燒雲／橘紅",
    stylePink:"偏粉紅",
    styleRainbow:"有彩虹機會",
    styleDull:"平淡機會高",
    styleNormal:"一般晚霞",
    photoTitle:"📸 攝影技巧",
    photoBody:`photo tips zh`
  }
};
function tr(k){return (T[lang||"en"]||T.en)[k]||k}
